src/objects/Vacation_Request__c.object
<CustomObject>
    <fields>
        <fullName>RequestType__c</fullName>
        <description>A list of available types</description>
        <inlineHelpText>A list of available types</inlineHelpText>
        <label>Request Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacation</fullName>
                </value>
                <value>
                    <fullName>Sick</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vacation Request</label>
    <nameField>
        <label>Vacation Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/vacationTableControllerTests.cls
@IsTest
public class vacationTableControllerTests {
	@IsTest
	static void test_countRequestTypes(){
		Integer entries = 0;
		List<String> expectedTypes = new List<String>{'Vacation', 'Sick', 'Unpaid'};

		Schema.DescribeFieldResult result = Vacation_Request__c.RequestType__c.getDescribe();
		List<Schema.PicklistEntry> typeEntries = result.getPicklistValues();

		for(Schema.PicklistEntry entry : typeEntries){
			System.assertEquals(entry.getValue(), expectedTypes[entries]);
			entries++;
		}
		System.assertEquals(entries, 3, 'Expected number of entries is 3, got '+entries);
	}
}